# rustfmt doc - https://rust-lang.github.io/rustfmt/

style_edition = "2024"
hard_tabs = false
tab_spaces = 2
max_width = 120
chain_width = 100
array_width = 100


# unstable features are only available in nightly channel
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"

wrap_comments = true
comment_width = 120

indent_style = "Visual"
imports_layout = "HorizontalVertical"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
condense_wildcard_suffixes = true
fn_params_layout = "Tall"
normalize_comments = true
normalize_doc_attributes = true
use_try_shorthand = true
use_small_heuristics = "Max"
